apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: snay4gitv-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: snay4gitv-nodejs 
  name: snay4gitv-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: snay4gitv-nodejs 
